app/src/main/java/com/dlsc/jfxcentral2/app/pages/OpenJFXPage.java
app/src/main/java/com/dlsc/jfxcentral2/app/service/LoadPullRequestsService.java
app/src/main/java/module-info.java
components/src/main/java/com/dlsc/jfxcentral2/components/PullRequestsView.java
components/src/main/java/com/dlsc/jfxcentral2/components/VideoGalleryTileView.java
components/src/main/java/com/dlsc/jfxcentral2/components/detailsbox/LibraryCoordinatesBox.java
components/src/main/java/com/dlsc/jfxcentral2/components/skins/PaginationControl2Skin.java
components/src/main/java/com/dlsc/jfxcentral2/components/tiles/VideoTileView.java
components/src/main/resources/com/dlsc/jfxcentral2/theme.css

Add "loading" message to library coordinates box and openjfx pull requests; #244 
Fixed VideoTileView in small size does not show preview correctly; #275 
Fixed The OpenJFXPage does not load data upon the first entry; #274

Add "loading" message Fixed OpenJFXPage

---

components/src/main/java/com/dlsc/jfxcentral2/components/ErrorView.java
components/src/main/java/com/dlsc/jfxcentral2/components/Header.java
components/src/main/java/com/dlsc/jfxcentral2/components/IconPreviewPane.java
components/src/main/resources/com/dlsc/jfxcentral2/theme.css
sampler/src/main/java/com/dlsc/jfxcentral2/demo/HelloErrorView.java

1. Add error view; #276 
2. Fixed Filter fields not aligned properly bug; #279 
3. Fixed The IkonliPackTileView may display a blank preview; #273

 Add error view;

---

components/src/main/java/com/dlsc/jfxcentral2/components/VideoGalleryTileView.java
components/src/main/java/com/dlsc/jfxcentral2/components/tiles/VideoTileView.java
components/src/main/resources/com/dlsc/jfxcentral2/theme.css

Fixed VideoTileView Fixed LOTW bullets 

---

app/src/main/java/com/dlsc/jfxcentral2/app/JFXCentral2App.java
app/src/main/java/com/dlsc/jfxcentral2/app/pages/CategoryPageBase.java
app/src/main/java/com/dlsc/jfxcentral2/app/pages/DetailsPageBase.java
app/src/main/java/com/dlsc/jfxcentral2/app/pages/ErrorPage.java
app/src/main/java/com/dlsc/jfxcentral2/app/pages/LegalPage.java
app/src/main/java/com/dlsc/jfxcentral2/app/pages/LoginPage.java
app/src/main/java/com/dlsc/jfxcentral2/app/pages/OpenJFXPage.java
app/src/main/java/com/dlsc/jfxcentral2/app/pages/PageBase.java
app/src/main/java/com/dlsc/jfxcentral2/app/pages/RefreshPage.java
app/src/main/java/com/dlsc/jfxcentral2/app/pages/StartPage.java
app/src/main/java/com/dlsc/jfxcentral2/app/pages/TeamPage.java
app/src/main/java/com/dlsc/jfxcentral2/app/pages/UserProfilePage.java
app/src/main/java/module-info.java
components/src/main/java/com/dlsc/jfxcentral2/components/MemberCellView.java
components/src/main/java/com/dlsc/jfxcentral2/components/Mode.java
components/src/main/java/com/dlsc/jfxcentral2/components/TeamView.java
components/src/main/java/com/dlsc/jfxcentral2/components/TopMenuBar.java
components/src/main/java/com/dlsc/jfxcentral2/components/TopPane.java
components/src/main/java/com/dlsc/jfxcentral2/components/headers/CategoryHeader.java
components/src/main/resources/com/dlsc/jfxcentral2/theme.css
pom.xml
sampler/src/main/java/com/dlsc/jfxcentral2/demo/HelloTeamView.java
sampler/src/main/java/com/dlsc/jfxcentral2/demo/components/HelloTopMenuBar.java

Add Team Page

---

app/src/main/java/com/dlsc/jfxcentral2/app/pages/TopContentPage.java
components/src/main/java/com/dlsc/jfxcentral2/components/SaveAndLikeButton.java
components/src/main/java/com/dlsc/jfxcentral2/components/skins/SaveAndLikeButtonSkin.java
components/src/main/java/com/dlsc/jfxcentral2/components/topcontent/TopContentContainerView.java
components/src/main/java/com/dlsc/jfxcentral2/components/topcontent/TopContentView.java
components/src/main/java/com/dlsc/jfxcentral2/utils/ModelObjectTool.java
components/src/main/java/module-info.java
components/src/main/resources/com/dlsc/jfxcentral2/theme.css
sampler/src/main/java/com/dlsc/jfxcentral2/demo/components/HelloSaveAndLikeButton.java
sampler/src/main/java/com/dlsc/jfxcentral2/demo/components/HelloTopContentView.java

Add TopContent Page

---

components/src/main/java/com/dlsc/jfxcentral2/components/CreditsView.java
components/src/main/java/com/dlsc/jfxcentral2/components/MemberCellView.java
components/src/main/java/com/dlsc/jfxcentral2/components/WebsiteChangesView.java
components/src/main/java/com/dlsc/jfxcentral2/components/gridview/ModelGridView.java
components/src/main/java/com/dlsc/jfxcentral2/components/skins/QuickLinkViewSkin.java
components/src/main/java/com/dlsc/jfxcentral2/components/topcontent/TopContentContainerView.java
components/src/main/resources/com/dlsc/jfxcentral2/theme.css

Mainly fixed bugs that appeared on the web page
1. #319 
2. #320  
3. #321 
4. #322 
5. #323 
6. #324 
7. #325 
8. #326

Mainly fixed bugs that appeared on the web page

---

components/src/main/java/com/dlsc/jfxcentral2/components/PullRequestsView.java
components/src/main/java/com/dlsc/jfxcentral2/components/detailsbox/BooksDetailsBox.java
components/src/main/java/com/dlsc/jfxcentral2/components/detailsbox/LibraryCoordinatesBox.java
components/src/main/java/com/dlsc/jfxcentral2/components/headers/BookDetailHeader.java
components/src/main/java/com/dlsc/jfxcentral2/components/headers/DetailHeader.java
components/src/main/java/com/dlsc/jfxcentral2/components/overviewbox/BookOverviewBox.java
components/src/main/java/com/dlsc/jfxcentral2/components/tiles/BlogTileView.java
components/src/main/java/com/dlsc/jfxcentral2/components/tiles/BookTileView.java
components/src/main/java/com/dlsc/jfxcentral2/components/tiles/LibraryTileView.java
components/src/main/java/com/dlsc/jfxcentral2/components/tiles/PersonTileView.java
components/src/main/java/com/dlsc/jfxcentral2/components/tiles/SimpleTileView.java
components/src/main/java/com/dlsc/jfxcentral2/components/tiles/ToolTileView.java
components/src/main/java/com/dlsc/jfxcentral2/components/tiles/VideoGalleryTileView.java
components/src/main/java/com/dlsc/jfxcentral2/components/topcontent/TopContentView.java
components/src/main/java/com/dlsc/jfxcentral2/utils/StringUtil.java
components/src/main/resources/com/dlsc/jfxcentral2/theme.css

1. #343 
2. #342 
3. #341 
4. #338 
5. #337 
6. #335

Fixed book's link

---

app/src/main/java/com/dlsc/jfxcentral2/app/pages/category/IconsCategoryPage.java
components/src/main/java/com/dlsc/jfxcentral2/components/PacksIconsView.java
components/src/main/java/com/dlsc/jfxcentral2/components/gridview/SimpleGridView.java
components/src/main/java/com/dlsc/jfxcentral2/components/headers/PacksIconsHeader.java
components/src/main/resources/com/dlsc/jfxcentral2/theme.css

Enhancement Icon Search

---

components/src/main/java/com/dlsc/jfxcentral2/components/PaginationControl.java
components/src/main/java/com/dlsc/jfxcentral2/components/skins/PaginationControlSkin.java
components/src/main/resources/com/dlsc/jfxcentral2/theme.css

Fixed PaginationControl should also have an empty message when there is no data available.

---

components/src/main/java/com/dlsc/jfxcentral2/components/PacksIconsView.java
components/src/main/java/com/dlsc/jfxcentral2/components/gridview/IkonDetailView.java
components/src/main/java/com/dlsc/jfxcentral2/model/IkonData.java
components/src/main/java/com/dlsc/jfxcentral2/utils/IkonliPackUtil.java
components/src/main/resources/com/dlsc/jfxcentral2/theme.css

1. #356 
2. #355 
3. #353 
4. #352 
5. #351 When the range selection is set to "icons," we can only align them as best as possible. However, when the range selection is set to "packs," we can achieve proper alignment.

Improved icons page

---

components/src/main/java/com/dlsc/jfxcentral2/components/DetailsContentPane.java
components/src/main/java/com/dlsc/jfxcentral2/components/skins/QuickLinkViewSkin.java
components/src/main/resources/com/dlsc/jfxcentral2/theme.css

1. #360 
2. #359 
3. #358 
4. #346

Fixed: Quicklinks do not work;

---

components/src/main/java/com/dlsc/jfxcentral2/components/DetailsContentPane.java
components/src/main/resources/com/dlsc/jfxcentral2/theme.css

Fixed: Too much gap between last details box and comments box

---

components/src/main/java/com/dlsc/jfxcentral2/components/DetailsContentPane.java
components/src/main/java/com/dlsc/jfxcentral2/components/detailsbox/LibraryCoordinatesBox.java
components/src/main/java/com/dlsc/jfxcentral2/components/gridview/IkonDetailView.java
components/src/main/java/com/dlsc/jfxcentral2/components/skins/QuickLinkViewSkin.java
components/src/main/java/com/dlsc/jfxcentral2/utils/FXUtil.java
components/src/main/java/com/dlsc/jfxcentral2/utils/IkonliPackUtil.java
components/src/main/java/com/dlsc/jfxcentral2/utils/NodeUtil.java
components/src/main/java/com/dlsc/jfxcentral2/utils/WebAPIUtil.java
components/src/main/resources/com/dlsc/jfxcentral2/theme.css
pom.xml

1. #362 
2. #365 
3. #367 
We are exploring a temporary solution to implement page navigation by executing JavaScript code.

Fixed  Link Becomes Unresponsive After Hovering and Bringing to Front

---

components/src/main/java/com/dlsc/jfxcentral2/components/QuickLinkView.java
components/src/main/java/com/dlsc/jfxcentral2/components/detailsbox/LibraryCoordinatesBox.java
components/src/main/java/com/dlsc/jfxcentral2/components/gridview/IkonDetailView.java
components/src/main/java/com/dlsc/jfxcentral2/components/skins/QuickLinkViewSkin.java
components/src/main/java/com/dlsc/jfxcentral2/components/skins/SponsorsViewSkin.java
components/src/main/java/com/dlsc/jfxcentral2/components/tiles/BookTileView.java
components/src/main/java/com/dlsc/jfxcentral2/components/tiles/IkonliPackTileView.java
components/src/main/java/com/dlsc/jfxcentral2/components/tiles/SimpleTileView.java
components/src/main/java/com/dlsc/jfxcentral2/utils/FilesUtil.java
components/src/main/java/com/dlsc/jfxcentral2/utils/IkonliPackUtil.java
components/src/main/java/com/dlsc/jfxcentral2/utils/WebAPIUtil.java
components/src/main/resources/com/dlsc/jfxcentral2/htmlviews/IkonDetailView.html
components/src/main/resources/com/dlsc/jfxcentral2/htmlviews/LibraryCoordinatesView.html
components/src/main/resources/com/dlsc/jfxcentral2/theme.css

1. #362 
2. #367 
3. #368 
4. #370 
(Temporary use of HtmlView or JS for a specific node)
Sponsored links modified to open in a new window; The source code for the ikonli pack project is also opened in a new window.
Fixed some CSS errors.

Fixed Copy button

---

app/src/main/java/com/dlsc/jfxcentral2/app/pages/OpenJFXPage.java
components/src/main/java/com/dlsc/jfxcentral2/components/CommentsView.java
components/src/main/java/com/dlsc/jfxcentral2/components/DetailsContentPane.java
components/src/main/java/com/dlsc/jfxcentral2/components/Header.java
components/src/main/java/com/dlsc/jfxcentral2/components/detailsbox/DetailsBoxBase.java
components/src/main/java/com/dlsc/jfxcentral2/components/detailsbox/LibraryCoordinatesBox.java
components/src/main/java/com/dlsc/jfxcentral2/components/gridview/IkonDetailView.java
components/src/main/resources/com/dlsc/jfxcentral2/htmlviews/LibraryCoordinatesView.html
components/src/main/resources/com/dlsc/jfxcentral2/theme.css

1. #373 
2. #375 
3. #372  
4. Use the Header component to replace the Header box in CommentsView.

After scrolling to the specified DetailsBox, the title should flash to remind the user

---

components/src/main/java/com/dlsc/jfxcentral2/components/CommentsView.java
components/src/main/java/com/dlsc/jfxcentral2/components/CustomTabPane.java
components/src/main/java/com/dlsc/jfxcentral2/components/DetailsContentPane.java
components/src/main/java/com/dlsc/jfxcentral2/components/LoginView.java
components/src/main/java/com/dlsc/jfxcentral2/components/MemberCellView.java
components/src/main/java/com/dlsc/jfxcentral2/components/PacksIconsView.java
components/src/main/java/com/dlsc/jfxcentral2/components/PaneBase.java
components/src/main/java/com/dlsc/jfxcentral2/components/QuickLinksContainer.java
components/src/main/java/com/dlsc/jfxcentral2/components/WeekLinksLiteView.java
components/src/main/java/com/dlsc/jfxcentral2/components/skins/ControlBaseSkin.java
components/src/main/java/com/dlsc/jfxcentral2/components/skins/FeatureViewSkin.java
components/src/main/java/com/dlsc/jfxcentral2/components/userprofile/ProfileContentPane.java
components/src/main/resources/com/dlsc/jfxcentral2/theme.css

Reduce UI rebuilding

---

app/src/main/java/com/dlsc/jfxcentral2/app/pages/LinksOfTheWeekPage.java
app/src/main/java/com/dlsc/jfxcentral2/app/pages/StartPage.java
components/src/main/java/com/dlsc/jfxcentral2/components/WeekLinksLiteView.java

Fixed LOTW;

---

components/src/main/resources/com/dlsc/jfxcentral2/theme.css

Fixed tabs padding

---

README.md

Adding a link to the high-level diagrams including module, library dependency and others (https://sourcespy.com/github/dlemmermannjfxcentral2/). Built directly from source and updated on schedule. Intended to simplify developer's introduction to the project.
In the spirit of transparency - I am the author of the diagrams. Hope contributors find it useful.

Update README.md with a link to project map

---

components/src/main/java/com/dlsc/jfxcentral2/components/Header.java
components/src/main/java/com/dlsc/jfxcentral2/components/PacksIconsView.java
components/src/main/java/com/dlsc/jfxcentral2/components/filters/SearchFilterView.java
components/src/main/java/com/dlsc/jfxcentral2/components/gridview/ModelGridView.java
components/src/main/resources/com/dlsc/jfxcentral2/theme.css

1. #387 
2. Fixe  the styling of the tabs;

Fixed: Filter toggle buttons are not showing up in small size;

---

components/src/main/java/com/dlsc/jfxcentral2/components/IkonliBrowser.java
pom.xml

After deleting cached versions
```
find ~/.m2 ~/.gradle | grep jpro-routing | xargs rm -r
find ~/.m2 ~/.gradle | grep jpro | grep 2023.2.2-SNAPSHOT | xargs rm -r
```
We get a lot of fixes.
#369 #227 #239 #362

web improvements

---

app/src/main/java/com/dlsc/jfxcentral2/app/stage/NavigationView.java
app/src/main/resources/jpro/html/defaultpage

fixes for #255 (horizontal scrollbar on web)
and #283 and #226 (routing history, showing title and redundant call to ""

more web improvements

---

components/src/main/java/com/dlsc/jfxcentral2/components/gridview/CellView.java

Fixed: Selecting an icon requires a double click

---

components/src/main/java/com/dlsc/jfxcentral2/components/headers/SimpleDetailHeader.java
components/src/main/java/com/dlsc/jfxcentral2/components/overviewbox/OverviewBox.java
components/src/main/java/com/dlsc/jfxcentral2/components/skins/QuickLinkViewSkin.java
components/src/main/resources/com/dlsc/jfxcentral2/theme.css

1. #395 
2. #362 
3. Fixe: the top padding of Overview is too large;

Fixed: Header Alignment Issue with Long Titles on Detail Page;

---

app/src/main/java/com/dlsc/jfxcentral2/app/pages/RefreshPage.java
components/src/main/java/com/dlsc/jfxcentral2/components/TopMenuBar.java
components/src/main/java/com/dlsc/jfxcentral2/components/headers/LinksOfTheWeekHeader.java

- add rss-feed-link
- fixed refresh-page with dev-filter
- fixed top-menu-bar, behaviour when clicking entries

release preparing fixes

---

app/src/main/java/com/dlsc/jfxcentral2/app/pages/LegalPage.java

Fixed Missing text in legal pages

---

app/src/main/java/com/dlsc/jfxcentral2/app/JFXCentral2App.java
components/src/main/java/com/dlsc/jfxcentral2/components/WelcomeView.java
components/src/main/resources/com/dlsc/jfxcentral2/theme.css

Add description information about Java FX on the welcome page

---

app/src/main/java/com/dlsc/jfxcentral2/app/JFXCentral2App.java
app/src/main/java/com/dlsc/jfxcentral2/app/pages/LinksOfTheWeekPage.java
components/src/main/java/com/dlsc/jfxcentral2/components/DetailsContentPane.java
components/src/main/java/com/dlsc/jfxcentral2/components/LinksOfTheWeekView.java
components/src/main/java/com/dlsc/jfxcentral2/utils/NodeUtil.java
components/src/main/resources/com/dlsc/jfxcentral2/theme.css

1. #417 
2. Automatically scroll to the top of the page when navigating to a new LOTW.
**Small /  Medium**
**Large**

enhancement Navigation between LOTW

---

components/pom.xml
components/src/main/java/com/dlsc/jfxcentral2/components/tiles/DownloadTileView.java
components/src/main/java/com/dlsc/jfxcentral2/utils/ModelObjectTool.java
components/src/main/java/com/dlsc/jfxcentral2/utils/images/CentralImageManager.java

image bugfixes

---

components/pom.xml
components/src/main/java/com/dlsc/jfxcentral2/components/TopMenuBar.java
pom.xml

1. Fix for SessionManager Bug on Desktop: Resolved the issue where sessionManager was returning null when the application was run on the desktop. This fix ensures consistent behavior across different environments. #436 
2. Upgraded gemsfx Dependency: Updated the gemsfx library to its latest version.
3. Added Missing javafx-web Module to component: Incorporated the javafx-web module into the component module. This addition resolves any dependency issues and ensures the correct functioning of components that rely on the javafx-web module.

Fix SessionManager Bug, Upgrade gemsfx Dependency, and Add Missing javafx-web Module

---

components/src/main/java/com/dlsc/jfxcentral2/components/detailsbox/DetailsBoxBase.java
components/src/main/java/com/dlsc/jfxcentral2/components/detailsbox/PersonsDetailsBox.java

Fix UI Refresh in VideosDetailsBox and Update Photo Clipping

---

app/src/main/java/com/dlsc/jfxcentral2/app/TrayIconManager.java
app/src/main/java/com/dlsc/jfxcentral2/app/pages/devtools/OnlineDevelopToolsPage.java
app/src/main/java/com/dlsc/jfxcentral2/app/pages/devtools/SvgPathExtractToolPage.java
app/src/main/java/com/dlsc/jfxcentral2/app/stage/CustomStage.java
components/pom.xml
components/src/main/java/com/dlsc/jfxcentral2/components/gridview/IkonDetailView.java
components/src/main/java/com/dlsc/jfxcentral2/utils/OSUtil.java
components/src/main/java/com/dlsc/jfxcentral2/utils/ReadTextFile.java
components/src/main/java/com/dlsc/jfxcentral2/utils/SVGPathExtractor.java
components/src/main/java/module-info.java
components/src/main/resources/com/dlsc/jfxcentral2/theme.css
devtools/src/main/java/com/dlsc/jfxcentral2/devtools/FileHandlerView.java
devtools/src/main/java/com/dlsc/jfxcentral2/devtools/pathextractor/RecentImageView.java
devtools/src/main/java/com/dlsc/jfxcentral2/devtools/pathextractor/SVGPathExtractorView.java
devtools/src/main/resources/com/dlsc/jfxcentral2/devtools/path-extractor-tips.md
pom.xml

Add download svg and copy path for each icon

---

components/src/main/java/com/dlsc/jfxcentral2/components/gridview/IkonDetailView.java
components/src/main/java/com/dlsc/jfxcentral2/utils/EmptyEntityResolver.java
components/src/main/java/com/dlsc/jfxcentral2/utils/FileUtil.java
components/src/main/java/com/dlsc/jfxcentral2/utils/SVGPathExtractor.java
components/src/main/resources/com/dlsc/jfxcentral2/theme.css

fix ikonli details views bugs

---

app/pom.xml
app/src/main/java/com/dlsc/jfxcentral2/app/JFXCentral2App.java
pom.xml

Fixed scrollpane issue,
updated JavaFX
redirect slf4j2 logging to log4j

Fixed scrollpane issue, updated JavaFX redirect slf4j2 logging to log4j

---

components/src/main/java/com/dlsc/jfxcentral2/components/overviewbox/UtilityOverviewBox.java
components/src/main/java/com/dlsc/jfxcentral2/utilities/pathextractor/SVGPathExtractorView.java
components/src/main/resources/com/dlsc/jfxcentral2/theme.css

The "SVG Path Extractor"page experiences vertical jitter on Website

---

components/src/main/java/com/dlsc/jfxcentral2/components/DoubleTextField.java
components/src/main/java/com/dlsc/jfxcentral2/components/overviewbox/ShowcaseOverviewBox.java
components/src/main/java/com/dlsc/jfxcentral2/components/overviewbox/UtilityOverviewBox.java
components/src/main/java/com/dlsc/jfxcentral2/utilities/pxemconverter/Px2EmConverter.java
components/src/main/java/com/dlsc/jfxcentral2/utilities/pxemconverter/Px2EmRules.java
components/src/main/java/com/dlsc/jfxcentral2/utilities/pxemconverter/Px2EmView.java
components/src/main/java/com/dlsc/jfxcentral2/utils/FileUtil.java
components/src/main/java/com/dlsc/jfxcentral2/utils/IkonUtil.java
components/src/main/resources/com/dlsc/jfxcentral2/theme.css
components/src/main/resources/com/dlsc/jfxcentral2/utilities/pxemconverter/css-px2em-rules.json

1. Convert All Pixel Values in CSS to "em" Units #489 
2. Hide fields in ShowcaseOverview box that are not used #526

Add Px2EmConverter; Hide fields in ShowcaseOverview box that are not used

---

app/src/main/java/com/dlsc/jfxcentral2/app/JFXCentral2App.java
components/src/main/java/com/dlsc/jfxcentral2/components/gridview/CellView.java
components/src/main/java/com/dlsc/jfxcentral2/components/skins/PaginationControl2Skin.java

1. Fixed 1: Need to Click Twice to Open IkonDetailView. #538 
2. Fixed 2: Focus Issues with Text Fields in Web Application on Android Browsers. #537

Fixed Need to Click Twice to Open IkonDetailView. And focus bug

---

components/src/main/java/com/dlsc/jfxcentral2/components/IconPreviewPane.java
components/src/main/java/com/dlsc/jfxcentral2/components/PacksIconsView.java

Asynchronously Load Icons

---

components/src/main/java/com/dlsc/jfxcentral2/utilities/effectdesigner/EffectFlowPane.java

Disable "AddEffect" button when the last effect is ColorInput;
Because ColorInput doesn't support setInput(Effect) method.

Disable add effect button when the last effect is ColorInput

---

app/src/main/java/com/dlsc/jfxcentral2/app/JFXCentral2App.java
app/src/main/java/com/dlsc/jfxcentral2/app/pages/DetailsPageBase.java
app/src/main/java/com/dlsc/jfxcentral2/app/pages/category/LearnCategoryPage.java
app/src/main/java/com/dlsc/jfxcentral2/app/pages/category/LearnJavaFXCategoryPage.java
app/src/main/java/com/dlsc/jfxcentral2/app/pages/category/LearnMobileCategoryPage.java
app/src/main/java/com/dlsc/jfxcentral2/app/pages/category/LearnRaspberryPiCategoryPage.java
app/src/main/java/com/dlsc/jfxcentral2/app/pages/details/LearnDetailsPage.java
components/src/main/java/com/dlsc/jfxcentral2/components/TopMenuBar.java
components/src/main/java/com/dlsc/jfxcentral2/components/filters/LearnFilterView.java
components/src/main/java/com/dlsc/jfxcentral2/components/hamburger/HamburgerMenuView.java
components/src/main/java/com/dlsc/jfxcentral2/components/headers/LearnDetailHeader.java
components/src/main/java/com/dlsc/jfxcentral2/components/overviewbox/LearnOverviewBox.java
components/src/main/java/com/dlsc/jfxcentral2/components/tiles/LearnTileView.java
components/src/main/java/com/dlsc/jfxcentral2/components/tiles/SimpleTileView.java
components/src/main/java/com/dlsc/jfxcentral2/utils/IkonUtil.java
components/src/main/java/com/dlsc/jfxcentral2/utils/ModelObjectTool.java
components/src/main/java/com/dlsc/jfxcentral2/utils/PageUtil.java
components/src/main/java/com/dlsc/jfxcentral2/utils/View.java
components/src/main/resources/com/dlsc/jfxcentral2/theme.css
pom.xml

Add Learn View

---

app/src/main/java/com/dlsc/jfxcentral2/app/pages/category/UtilitiesCategoryPage.java
components/src/main/java/com/dlsc/jfxcentral2/components/TopMenuBar.java
components/src/main/java/com/dlsc/jfxcentral2/components/gridview/ModelGridView.java
components/src/main/java/com/dlsc/jfxcentral2/components/overviewbox/UtilityOverviewBox.java
components/src/main/java/com/dlsc/jfxcentral2/components/tiles/UtilityTileView.java
components/src/main/java/com/dlsc/jfxcentral2/utilities/cssplayground/CssPlaygroundView.java
components/src/main/java/com/dlsc/jfxcentral2/utilities/cssplayground/impl/CssShowcaseViewSkin.java
components/src/main/java/com/dlsc/jfxcentral2/utilities/effectdesigner/EffectDesignerView.java
components/src/main/java/com/dlsc/jfxcentral2/utilities/effectdesigner/EffectFlowPane.java
components/src/main/java/com/dlsc/jfxcentral2/utilities/effectdesigner/editor/ColorInputEditor.java
components/src/main/java/com/dlsc/jfxcentral2/utilities/effectdesigner/editor/DisplacementMapEditor.java
components/src/main/java/com/dlsc/jfxcentral2/utilities/effectdesigner/editor/DropShadowEditor.java
components/src/main/java/com/dlsc/jfxcentral2/utilities/effectdesigner/editor/EffectPropertyFactory.java
components/src/main/java/com/dlsc/jfxcentral2/utilities/effectdesigner/editor/ImageInputEditor.java
components/src/main/java/com/dlsc/jfxcentral2/utilities/effectdesigner/editor/InnerShadowEditor.java
components/src/main/java/com/dlsc/jfxcentral2/utilities/effectdesigner/editor/PerspectiveTransformEditor.java
components/src/main/java/com/dlsc/jfxcentral2/utilities/effectdesigner/editor/ReflectionEditor.java
components/src/main/resources/com/dlsc/jfxcentral2/theme.css
pom.xml

Fix "Load More" button should not be initially enabled when nothing else can be loaded

---

components/src/main/java/com/dlsc/jfxcentral2/components/filters/DocumentationFilterView.java
components/src/main/java/com/dlsc/jfxcentral2/components/filters/SimpleModelObjectSearchFilterView.java

Set the model to display in random order by default

---

components/src/main/java/com/dlsc/jfxcentral2/components/TopMenuBar.java
components/src/main/resources/com/dlsc/jfxcentral2/theme.css

Add a Home button to make it easy to return to the home page.

---

components/src/main/resources/com/dlsc/jfxcentral2/theme.css

Fixed icon color on light background

---

app/src/main/java/com/dlsc/jfxcentral2/app/pages/DetailsPageBase.java
components/src/main/java/com/dlsc/jfxcentral2/components/SearchResultCell.java
components/src/main/java/com/dlsc/jfxcentral2/components/TopMenuBar.java
components/src/main/java/com/dlsc/jfxcentral2/components/detailsbox/LearnDetailBox.java
components/src/main/java/com/dlsc/jfxcentral2/components/filters/LearnFilterView.java
components/src/main/java/com/dlsc/jfxcentral2/components/hamburger/HamburgerMenuView.java
components/src/main/java/com/dlsc/jfxcentral2/components/headers/LearnDetailHeader.java
components/src/main/java/com/dlsc/jfxcentral2/components/skins/FeatureViewSkin.java
components/src/main/java/com/dlsc/jfxcentral2/utils/IkonUtil.java
components/src/main/java/com/dlsc/jfxcentral2/utils/ModelObjectTool.java
components/src/main/java/com/dlsc/jfxcentral2/utils/QuickLinksGenerator.java
components/src/main/resources/com/dlsc/jfxcentral2/theme.css
pom.xml

1. Add detail box for "Learn"  #564 
2. Learn section: ordering of the content; #558 
3. Fix missing button to external link for source code; #561 
4. Add FeaturedImage to library

Add detail box for "Learn" 

---

app/src/main/java/com/dlsc/jfxcentral2/app/pages/DetailsPageBase.java
app/src/main/java/com/dlsc/jfxcentral2/app/pages/details/LearnDetailsPage.java
components/src/main/java/com/dlsc/jfxcentral2/components/DetailsContentPane.java
components/src/main/java/com/dlsc/jfxcentral2/components/LearnPaginationBox.java
components/src/main/java/com/dlsc/jfxcentral2/components/detailsbox/DocumentationDetailsBox.java
components/src/main/java/com/dlsc/jfxcentral2/components/filters/SearchFilterView.java
components/src/main/java/com/dlsc/jfxcentral2/components/overviewbox/LearnOverviewBox.java
components/src/main/resources/com/dlsc/jfxcentral2/theme.css

1. Add "Previous" and "Next" buttons to LearnDetailsPage. #563 
2. Add detail box for "Learn". #564 
3. Add detail box for "Documentation". #566 
4. Fix: A previous submission resulted in the misalignment of the SearchFilterView and the ModelView. #573

Enhancement learn ui

---

components/src/main/java/com/dlsc/jfxcentral2/components/LearnPaginationBox.java
components/src/main/java/com/dlsc/jfxcentral2/components/tiles/SimpleTileView.java
components/src/main/resources/com/dlsc/jfxcentral2/theme.css

1. Always show 'Previous' and 'Next' buttons at bottom;
2. Add 'Learn' badge to PersonTileView

Always show 'Previous' and 'Next' buttons at bottom; Add 'Learn' badge to PersonTileView

---

components/src/main/java/com/dlsc/jfxcentral2/components/TopMenuBar.java
components/src/main/java/com/dlsc/jfxcentral2/components/hamburger/HamburgerMenuView.java

Move "Documentation" and "Downloads" into "Resources" menu.

---

app/pom.xml
app/src/main/java/com/dlsc/jfxcentral2/app/JFXCentral2App.java
app/src/main/java/com/dlsc/jfxcentral2/app/filters/FooterFilter.java
app/src/main/java/com/dlsc/jfxcentral2/app/pages/PageBase.java
pom.xml

Switchting back to JavaFX20,
Added Incremental Loading,
The Footer is now only created once.

Huge performance improvement 10x,

---

app/pom.xml
app/src/main/java/com/dlsc/jfxcentral2/app/JFXCentral2App.java
app/src/main/java/com/dlsc/jfxcentral2/app/pages/SingleIconPage.java
app/src/main/java/module-info.java
components/src/main/java/com/dlsc/jfxcentral2/components/gridview/IkonDetailView.java
components/src/main/java/com/dlsc/jfxcentral2/components/headers/DetailHeader.java
components/src/main/java/com/dlsc/jfxcentral2/components/headers/DetailHeaderBase.java
components/src/main/java/com/dlsc/jfxcentral2/components/headers/SingleIconDetailHeader.java
components/src/main/java/com/dlsc/jfxcentral2/model/IconInfo.java
components/src/main/java/com/dlsc/jfxcentral2/model/IconInfoBuilder.java
components/src/main/java/com/dlsc/jfxcentral2/utils/IkonliPackUtil.java
components/src/main/resources/com/dlsc/jfxcentral2/theme.css

Add SingleIconPage

---

mobile/src/main/java/com/dlsc/jfxcentral2/mobile/LotwPageView.java
mobile/src/main/resources/com/dlsc/jfxcentral2/mobile/mobile.css
sampler/src/main/java/com/dlsc/jfxcentral2/demo/mobile/HelloLotwPageView.java

This commit adds two new classes, LotwPageView.java and HelloLotwPageView.java. LotwPageView provides functionalities to display links of the week, enabling sorting, and displaying based on creation dates. It also includes the addition of necessary style properties in the mobile.css file. HelloLotwPageView is a demo class displaying an instance of LotwPageView.

Add LotwPageView and HelloLotwPageView classes

---

components/src/main/java/com/dlsc/jfxcentral2/components/PrettyScrollPane.java
components/src/main/java/module-info.java
mobile/src/main/java/com/dlsc/jfxcentral2/mobile/componenets/MobileCategoryHeader.java
mobile/src/main/java/com/dlsc/jfxcentral2/mobile/componenets/MobileDevelopToolBar.java
mobile/src/main/java/com/dlsc/jfxcentral2/mobile/componenets/ModelListCell.java
mobile/src/main/java/com/dlsc/jfxcentral2/mobile/componenets/ModelListView.java
mobile/src/main/java/com/dlsc/jfxcentral2/mobile/home/CategoryAdvancedView.java
mobile/src/main/java/com/dlsc/jfxcentral2/mobile/home/CategoryPreviewView.java
mobile/src/main/java/com/dlsc/jfxcentral2/mobile/pages/MobileHomePage.java
mobile/src/main/java/com/dlsc/jfxcentral2/mobile/pages/MobileLinksOfTheWeekPage.java
mobile/src/main/java/com/dlsc/jfxcentral2/mobile/pages/category/MobileBlogsCategoryPage.java
mobile/src/main/java/com/dlsc/jfxcentral2/mobile/pages/category/MobileBooksCategoryPage.java
mobile/src/main/java/com/dlsc/jfxcentral2/mobile/pages/category/MobileCategoryPageBase.java
mobile/src/main/java/com/dlsc/jfxcentral2/mobile/pages/category/MobileCompaniesCategoryPage.java
mobile/src/main/java/com/dlsc/jfxcentral2/mobile/pages/category/MobileLearnCategoryPage.java
mobile/src/main/java/com/dlsc/jfxcentral2/mobile/pages/category/MobileLibrariesCategoryPage.java
mobile/src/main/java/com/dlsc/jfxcentral2/mobile/pages/category/MobilePeopleCategoryPage.java
mobile/src/main/java/com/dlsc/jfxcentral2/mobile/pages/category/MobileShowcasesCategoryPage.java
mobile/src/main/java/com/dlsc/jfxcentral2/mobile/pages/category/MobileTipCategoryPage.java
mobile/src/main/java/com/dlsc/jfxcentral2/mobile/pages/category/MobileToolsCategoryPage.java
mobile/src/main/java/com/dlsc/jfxcentral2/mobile/pages/category/MobileTutorialsCategoryPage.java
mobile/src/main/java/com/dlsc/jfxcentral2/mobile/pages/category/MobileVideosCategoryPage.java
mobile/src/main/java/com/dlsc/jfxcentral2/mobile/skin/MainPageSkin.java
mobile/src/main/resources/com/dlsc/jfxcentral2/mobile/mobile.css

- Created a new category page for mobile devices.
- Made layout adjustments to reduce component heights, decrease top spacing, and minimize excessive gaps.
- Enhanced screen real estate usage to display more content.

Add mobile category page and adjust layout

---

app/src/main/java/com/dlsc/jfxcentral2/app/pages/MobileRefreshPage.java
app/src/main/java/com/dlsc/jfxcentral2/app/pages/RefreshPage.java
app/src/main/java/com/dlsc/jfxcentral2/app/utils/RepositoryUpdater.java

The repository update logic previously found in MobileRefreshPage and RefreshPage has been moved to a new class, RepositoryUpdater. This refactor improves the code structure by separating concerns, making the logic reusable and simplifying the parent classes.

Refactor repository update logic into separate class

---

app/src/main/java/com/dlsc/jfxcentral2/app/JFXCentral2App.java
app/src/main/java/com/dlsc/jfxcentral2/app/JFXCentral2MobileApp.java
components/src/main/java/com/dlsc/jfxcentral2/utils/PagePath.java
components/src/main/resources/com/dlsc/jfxcentral2/theme.css
mobile/src/main/java/com/dlsc/jfxcentral2/mobile/pages/MobileHomePage.java
mobile/src/main/java/com/dlsc/jfxcentral2/mobile/pages/MobileSearchPage.java
mobile/src/main/java/com/dlsc/jfxcentral2/mobile/skin/MainPageSkin.java
mobile/src/main/java/com/dlsc/jfxcentral2/mobile/utils/PreferredFocusedNodeProvider.java
mobile/src/main/java/module-info.java
mobile/src/main/resources/com/dlsc/jfxcentral2/mobile/mobile.css

1. A new Search page was added to the mobile version of the application. To accommodate this, the search bar on the home page was modified to redirect to the Search page when clicked. Additional enhancements include updated styling for better UI experience and automatic focusing on the search bar when the Search page is opened.
2. Increase the bottom margin of the navigation buttons to make it easier for users to click.

Add search functionality to mobile version

---

mobile/src/main/java/com/dlsc/jfxcentral2/mobile/pages/category/MobileBlogsCategoryPage.java
mobile/src/main/resources/com/dlsc/jfxcentral2/mobile/mobile.css

Update UI in mobile blogs category page;Added a new style class "blogs-category-page" to the MobileBlogsCategoryPage.java. Also updated mobile.css to alter the avatar type from CIRCLE to PLAIN in the list view of the blogs category page for a more consistent user interface.

fix: Correct incomplete image display in Blogs list

---

app/src/main/java/com/dlsc/jfxcentral2/app/JFXCentral2MobileApp.java
components/src/main/java/com/dlsc/jfxcentral2/utils/MobileLinkUtil.java
components/src/main/java/com/dlsc/jfxcentral2/utils/MobileRouter.java
components/src/main/java/com/dlsc/jfxcentral2/utils/Navigator.java
mobile/src/main/java/com/dlsc/jfxcentral2/mobile/components/MobileCategoryHeader.java
mobile/src/main/java/com/dlsc/jfxcentral2/mobile/components/MobileDevelopToolBar.java
mobile/src/main/java/com/dlsc/jfxcentral2/mobile/pages/MobileHomePage.java
sampler/src/main/java/com/dlsc/jfxcentral2/demo/mobile/HelloMobileHomePage.java

Upgraded the MobileHomePage class to use the Singleton pattern. Redesigned the mobile navigation system by adding a history tracking feature which allows users to navigate back/forward on the mobile interface. Also introduced navigation buttons on the mobile development toolbar.

Implement Singleton pattern and enhance mobile navigation

---

mobile/src/main/java/com/dlsc/jfxcentral2/mobile/components/WelcomePageView.java

Added a line of code in the WelcomePageView class to initially set the page index randomly. This change aims to display various pages in a randomized manner upon launching the application, enhancing user experience by providing a diverse starting point each time.

Set initial page index randomly in WelcomePageView

---

mobile/src/main/java/com/dlsc/jfxcentral2/mobile/components/BottomMenuBar.java
mobile/src/main/resources/com/dlsc/jfxcentral2/mobile/mobile.css

UI elements have been adjusted in the mobile.css file, including changing shadow effects to border properties for a more modern and clean look. In the BottomMenuBar.java file, the interaction with the home button has been changed from reacting on mouse click to mouse press for a smoother user experience.

Update UI elements and modify button interaction

---

mobile/src/main/java/com/dlsc/jfxcentral2/mobile/components/LearnCategoryBox.java
mobile/src/main/java/com/dlsc/jfxcentral2/mobile/components/LearnListCell.java
mobile/src/main/java/com/dlsc/jfxcentral2/mobile/components/LearnPagination.java
mobile/src/main/java/com/dlsc/jfxcentral2/mobile/pages/MobileHomePage.java
mobile/src/main/java/com/dlsc/jfxcentral2/mobile/pages/category/MobileLearnCategoryPage.java
mobile/src/main/java/com/dlsc/jfxcentral2/mobile/pages/details/MobileLearnDetailsPage.java
mobile/src/main/resources/com/dlsc/jfxcentral2/mobile/mobile.css

The code changes involve updating the layout and functionality of the mobile learn page. This includes the addition of a LearnCategoryBox and LearnListCell, as well as a LearnPagination model for better navigation. The code also includes changes to the CSS for the new components, ensuring a coherent look and feel.

Add Learn Part and related pages.

---

README.md

Added steps for running the mobile app via Maven. Also updated the description to reflect support for mobile in addition to desktop and web versions.

Update README to include mobile app instructions

---

components/src/main/java/com/dlsc/jfxcentral2/components/MastodonInputField.java
components/src/main/java/com/dlsc/jfxcentral2/components/MastodonShareView.java
components/src/main/java/com/dlsc/jfxcentral2/components/SocialLinksView.java
components/src/main/java/com/dlsc/jfxcentral2/components/headers/DetailHeaderBase.java
components/src/main/java/com/dlsc/jfxcentral2/utils/RegistryHelper.java
components/src/main/resources/com/dlsc/jfxcentral2/theme.css

FYI @leewyatt, this is work-in-progress, but I already created pull request so you can maybe advise me if this is a good approach with a dialog and how to style it.
Fixes #316

Mastodon share button (via dialog)
