- components/src/main/java/com/dlsc/jfxcentral2/components/WebsiteChangesView.java
> In small sizes, blank QuickLinks should be filtered out.

- components/src/main/java/com/dlsc/jfxcentral2/components/PacksIconsView.java
- components/src/main/java/com/dlsc/jfxcentral2/components/tiles/SimpleTileView.java
- components/src/main/resources/com/dlsc/jfxcentral2/theme.css
1. #413 
2. #411 
3. #410 
4. #409
> Fixed: Large Gaps in Library Preview Pane on Desktop Client

- README.md
- app/src/main/java/com/dlsc/jfxcentral2/app/RepositoryManager.java
- app/src/main/java/com/dlsc/jfxcentral2/app/TrayIconManager.java
- components/src/main/java/com/dlsc/jfxcentral2/components/WelcomeView.java
1. #433 
However, I've retained the original link direction in "Stay in loop" for GitHub and made no changes there.
> Updated Links for jfxcentral2 and jfxcentral-data

- app/src/main/java/com/dlsc/jfxcentral2/app/JFXCentral2App.java
- app/src/main/java/com/dlsc/jfxcentral2/app/TrayIconManager.java
- app/src/main/java/com/dlsc/jfxcentral2/app/pages/category/DocumentationCategoryPage.java
- components/src/main/java/com/dlsc/jfxcentral2/components/TopMenuBar.java
- components/src/main/java/com/dlsc/jfxcentral2/components/filters/DocumentationFilterView.java
- components/src/main/java/com/dlsc/jfxcentral2/components/hamburger/HamburgerMenuView.java
- components/src/main/java/com/dlsc/jfxcentral2/components/tiles/DocumentationTileView.java
- components/src/main/java/com/dlsc/jfxcentral2/components/tiles/SimpleTileView.java
- components/src/main/java/com/dlsc/jfxcentral2/utils/IkonUtil.java
- components/src/main/resources/com/dlsc/jfxcentral2/theme.css
- pom.xml
- #377 
This PR adds a dedicated documentation page aimed at centralizing essential JavaFX development resources. The newly introduced page includes:
CSS Reference Guide: Detailing JavaFX-specific CSS styling nuances.
FXML Reference Documentation: Covering the intricacies of defining UI layouts using FXML.
API Documentation: Serving as a complete reference for JavaFX classes, methods, and functionalities.
Development Handbook: Encompassing best practices, handy tips, and methodical guidance for JavaFX development.
Beginner's Guide: Providing a step-by-step introduction to JavaFX for those new to the framework, helping them get started effectively.
By consolidating these resources in one place, we aim to facilitate a smoother and more comprehensive development experience for both novice …
> Add reference documentation page.

- components/src/main/java/com/dlsc/jfxcentral2/components/FlipView.java
- components/src/main/java/com/dlsc/jfxcentral2/components/skins/FlipViewSkin.java
- components/src/main/java/com/dlsc/jfxcentral2/components/tiles/TileView.java
- sampler/src/main/java/com/dlsc/jfxcentral2/demo/components/HelloFlipView.java
1. #470 
2. Fixed: despite setting the 'FocusTraversable' attribute of the textarea to 'false', selecting text caused the interface to jump unpredictably when attempting to close it.
> FlipPane should create back of pane lazily

- components/src/main/java/com/dlsc/jfxcentral2/components/tiles/TileView.java
There is a current issue where, despite button 2 being hidden, the separator between button 1 and button 2 remains visible.
> Separator Visibility Issue between Button 1 and Button 2

- components/src/main/java/com/dlsc/jfxcentral2/components/CustomSearchField.java
- components/src/main/java/com/dlsc/jfxcentral2/components/CustomSearchFieldSkin.java
- components/src/main/java/com/dlsc/jfxcentral2/components/PacksIconsView.java
- components/src/main/java/com/dlsc/jfxcentral2/components/filters/SearchFilterView.java
- components/src/main/java/com/dlsc/jfxcentral2/utilities/paintpicker/impl/NamedColorsView.java
- components/src/main/java/com/dlsc/jfxcentral2/utils/DaemonScheduledExecutorService.java
- components/src/main/java/module-info.java
- components/src/main/resources/com/dlsc/jfxcentral2/theme.css
- sampler/src/main/java/com/dlsc/jfxcentral2/demo/components/HelloCustomSearchField.java
1. Fix SearchTextField Does Not Create Left and Right Nodes on Mobile Devices; #530 
2. Fix Background ExecutorService Prevents JVM Exit; #529
> Resolve Mobile Node Initialization in SearchTextField and Ensure JVM Exit by Fixing Background ExecutorService

- app/src/main/java/com/dlsc/jfxcentral2/app/JFXCentral2App.java
- app/src/main/java/com/dlsc/jfxcentral2/app/pages/SingleIconPage.java
- components/src/main/java/com/dlsc/jfxcentral2/components/gridview/IkonDetailView.java
- components/src/main/java/com/dlsc/jfxcentral2/components/gridview/IkonGridView.java
- components/src/main/java/com/dlsc/jfxcentral2/components/headers/SingleIconDetailHeader.java
- components/src/main/java/com/dlsc/jfxcentral2/model/IconInfo.java
- components/src/main/java/com/dlsc/jfxcentral2/model/IconInfoBuilder.java
- components/src/main/resources/com/dlsc/jfxcentral2/theme.css
- conveyor.conf
1.  Implemented Detail button for direct access to icon detail pages. 
2. Added URL schemes support. Now, links like `jfxcentral://icons/materialdesign/mdi-check-circle-outline` and `jfxcentral://blogs` can open and navigate within the desktop client to respective resources.
> Enhancement icon details page and Update Conveyor config

- components/src/main/resources/com/dlsc/jfxcentral2/theme.css
- mobile/src/main/java/com/dlsc/jfxcentral2/mobile/home/MobileHomePage.java
- mobile/src/main/java/com/dlsc/jfxcentral2/mobile/home/WeekLinksView.java
- mobile/src/main/resources/com/dlsc/jfxcentral2/mobile/mobile.css
The multiple differences in behavior between the desktop and mobile versions of WeekLinksLiteView were leading to a convoluted class. They have been separated into multiple classes, leading to cleaner and more easily maintainable code. Additionally, some unused imports have been removed. The mobile version is now housed separately in WeekLinksView class.
> Separate mobile and desktop versions of WeekLinksLiteView

- components/src/main/java/com/dlsc/jfxcentral2/components/headers/CategoryHeader.java
- components/src/main/java/com/dlsc/jfxcentral2/utils/MobileLinkUtil.java
- mobile/src/main/java/com/dlsc/jfxcentral2/mobile/components/ModelListCell.java
- mobile/src/main/java/com/dlsc/jfxcentral2/mobile/components/ModelListView.java
- mobile/src/main/java/com/dlsc/jfxcentral2/mobile/utils/ListViewUtil.java
Refactored the event handlers for clicking on list items and hyperlinks. Clicks are now only activated when the mouse has not moved between the press and release events. A new ListViewUtil class has been created to encapsulate this logic for list items, cleaning up code in other areas of the application.
> Update click handling in list and hyperlinks

- mobile/src/main/java/com/dlsc/jfxcentral2/mobile/components/MobileDevelopToolBar.java
The WidthType enum in MobileDevelopToolBar has been refactored to DeviceType. This change introduces a more granular representation of various iPhone models along with their description, width, and height. It also includes the StringConverter for the DeviceType ComboBox selection, allowing users to choose a device instead of just the width for the layout design.
> Refactor WidthType to DeviceType in MobileDevelopToolBar

- mobile/src/main/java/com/dlsc/jfxcentral2/mobile/pages/MobileHomePage.java
- mobile/src/main/resources/com/dlsc/jfxcentral2/mobile/mobile.css
The existing search button has been replaced with a creatSearchCancelButton method. This button now handles toggling between search and normal content types. Previously unused imports were also removed. Additionally, minor CSS adjustments were made for the search-text-field's button.
> Refactor search button functionality in MobileHomePage

- mobile/src/main/java/com/dlsc/jfxcentral2/mobile/components/MobileCategoryHeader.java
- mobile/src/main/java/com/dlsc/jfxcentral2/mobile/pages/details/MobileBlogDetailsPage.java
- mobile/src/main/java/com/dlsc/jfxcentral2/mobile/pages/details/MobileBookDetailsPage.java
- mobile/src/main/java/com/dlsc/jfxcentral2/mobile/pages/details/MobileCompanyDetailsPage.java
- mobile/src/main/java/com/dlsc/jfxcentral2/mobile/pages/details/MobileLearnDetailsPage.java
- mobile/src/main/java/com/dlsc/jfxcentral2/mobile/pages/details/MobileLibraryDetailsPage.java
- mobile/src/main/java/com/dlsc/jfxcentral2/mobile/pages/details/MobilePersonDetailsPage.java
- mobile/src/main/java/com/dlsc/jfxcentral2/mobile/pages/details/MobileShowcaseMobileDetailsPage.java
- mobile/src/main/java/com/dlsc/jfxcentral2/mobile/pages/details/MobileTipDetailsPage.java
- mobile/src/main/java/com/dlsc/jfxcentral2/mobile/pages/details/MobileToolDetailsPage.java
- mobile/src/main/java/com/dlsc/jfxcentral2/mobile/pages/details/MobileTutorialDetailsPage.java
- mobile/src/main/java/com/dlsc/jfxcentral2/mobile/pages/details/MobileVideoDetailsPage.java
1. Remove header image in detail pages
2. Removed redundant overriden method `goBackLink()` from `MobileCategoryHeader` in all details pages. This simplifies how `MobileCategoryHeader` is instantiated, reducing code duplication and making the code more maintainable.
> Simplify MobileCategoryHeader instantiation

- mobile/src/main/java/com/dlsc/jfxcentral2/mobile/components/MobileBlogOverviewBox.java
Added a line of code to sort blog posts in descending order based on their published date. This ensures that the most recent posts appear first in the MobileBlogOverviewBox.
> Sort blog posts by date

- mobile/src/main/java/com/dlsc/jfxcentral2/mobile/components/MobilePersonDetailView.java
- mobile/src/main/java/com/dlsc/jfxcentral2/mobile/home/CategoryPreviewView.java
- mobile/src/main/java/com/dlsc/jfxcentral2/mobile/pages/MobileHomePage.java
- mobile/src/main/java/com/dlsc/jfxcentral2/mobile/pages/details/MobilePersonDetailsPage.java
- mobile/src/main/resources/com/dlsc/jfxcentral2/mobile/mobile.css
Simplified MobilePersonDetailsPage by removing a complex header and details content creation. Introduced MobilePersonDetailView supporting the view with person details. The changes include the display of badges indicating the person's contribution status and an update in styling the details page.
> Refactor MobilePersonDetailsPage and add MobilePersonDetailView

- app/src/main/java/com/dlsc/jfxcentral2/app/JFXCentral2MobileApp.java
- components/src/main/java/com/dlsc/jfxcentral2/events/OpenWebLinkEvent.java
- components/src/main/java/com/dlsc/jfxcentral2/utils/MobileLinkUtil.java
- mobile/src/main/java/com/dlsc/jfxcentral2/mobile/components/ModelListView.java
- mobile/src/main/java/com/dlsc/jfxcentral2/mobile/pages/category/MobileDocPage.java
An update has been made to support the opening of documentation links from the mobile application. New classes for handling and dispatching link opening events have been introduced. The functionality caters for either native or external browser link opening, enhancing the user's browsing experience directly from within the app.
> Add documentation page

- mobile/src/main/java/com/dlsc/jfxcentral2/mobile/components/BottomMenuBar.java
Expanded the action listener of the home button in the BottomMenuBar class. Now when the home button is being displayed and is clicked, it hides the search view and displays the normal content. If it's not being displayed, it navigates to the home page like before.
> Update home button action in BottomMenuBar

- mobile/src/main/java/com/dlsc/jfxcentral2/mobile/pages/MobileHomePage.java
- mobile/src/main/java/com/dlsc/jfxcentral2/mobile/skin/MainPageSkin.java
The update incorporates lifecycle methods for mobile views in the MainPageSkin class. Now, before an old view disappears or a new view appears, optional Runnable tasks are executed. This allows for smoother transitions between different views. A viewDidLoad method was also added to the MobileHomePage class for setting the content type on view appearance.
> Implement lifecycle methods for mobile views

- mobile/src/main/java/com/dlsc/jfxcentral2/mobile/components/LearnPagination.java
- mobile/src/main/java/com/dlsc/jfxcentral2/mobile/components/LotwPagination.java
- mobile/src/main/java/com/dlsc/jfxcentral2/mobile/components/MobilePageHeader.java
- mobile/src/main/java/com/dlsc/jfxcentral2/mobile/components/MobilePagination.java
- mobile/src/main/java/com/dlsc/jfxcentral2/mobile/components/MobilePersonDetailView.java
- mobile/src/main/java/com/dlsc/jfxcentral2/mobile/home/CategoryPreviewView.java
- mobile/src/main/java/com/dlsc/jfxcentral2/mobile/home/CategoryView.java
- mobile/src/main/java/com/dlsc/jfxcentral2/mobile/pages/MobileLinksOfTheWeekPage.java
- mobile/src/main/java/com/dlsc/jfxcentral2/mobile/pages/category/MobileCategoryPageBase.java
- mobile/src/main/java/com/dlsc/jfxcentral2/mobile/pages/category/MobileLearnCategoryPage.java
- mobile/src/main/java/com/dlsc/jfxcentral2/mobile/pages/details/MobileLearnDetailsPage.java
- mobile/src/main/resources/com/dlsc/jfxcentral2/mobile/mobile.css
1. Add LotwPagination component.
2. Add LearnPagination component.
3. Wrap Details Page header text for better display.
4. Fix sorting error on Learn category page.
5. Remove "Related" text from header.
6. Add pressed styles for back button, more button, and others.
7. Update css
- #640 
- #643
> Add pagination components and enhance header text display, update styles

- app/src/main/java/com/dlsc/jfxcentral2/app/pages/MobileRefreshPage.java
- mobile/src/main/resources/com/dlsc/jfxcentral2/mobile/mobile.css
Refactored MobileRefreshPage to initialize UI based on first-time setup or update mode. Introduced `setupFirstTimeUI` and `setupUpdateUI` methods to separate logic. Updated CSS to style the new update UI elements.
> Add first-time setup and update UI to MobileRefreshPage

- components/src/main/java/com/dlsc/jfxcentral2/components/MobileSearchTextField.java
- mobile/src/main/java/com/dlsc/jfxcentral2/mobile/pages/MobileHomePage.java
- mobile/src/main/resources/com/dlsc/jfxcentral2/mobile/mobile.css
Introduce a clear button on the right side of MobileSearchTextField for better user experience. Refactor MobileHomePage to include the new clear button and style it properly in CSS.
The "Clear Text button" will only be displayed when the SearchField is not empty.
- **Category Page**
- **Home Page**
> Add clear button to MobileSearchTextField

- .github/workflows/ios.yml
Added specific versions for GraalVM and JDK to the iOS GitHub Actions workflow. This ensures consistent build environments and enhances compatibility with the project's requirements.
> Configure GraalVM and JDK in iOS workflow

- .github/workflows/ios.yml
Updated the iOS GitHub Actions workflow to correct the syntax for setting up Gluon's GraalVM. This change shifts from using direct assignment to the `with` parameter block for better compatibility and clarity.
> Fix GraalVM setup syntax in iOS workflow

- mobile/src/main/java/com/dlsc/jfxcentral2/mobile/components/CategorySelectionView.java
This PR introduces functionality to the CategorySelectionView to automatically select a category button when its associated path matches the current path. This enhances user experience by visually indicating which category is currently active or being viewed.
> Ensure Category Buttons Are Selected When Paths Match

- app/src/main/java/com/dlsc/jfxcentral2/app/JFXCentral2App.java
- app/src/main/java/com/dlsc/jfxcentral2/app/pages/LinksOfTheWeekPage.java
- components/src/main/java/com/dlsc/jfxcentral2/components/LinksOfTheWeekView.java
- components/src/main/resources/com/dlsc/jfxcentral2/theme.css
- sampler/src/main/java/com/dlsc/jfxcentral2/demo/components/HelloLinksOfTheWeekView.java
This PR adds support for direct links to specific dates, e.g. /links/2024-07-28, allowing users to navigate directly to a given "Links of the Week" entry.
- #654
> Add direct URLs for the links

- app/src/main/java/com/dlsc/jfxcentral2/app/JFXCentral2App.java
Seemed related exception and OOM on JPro Server.
Better to remove it.
> Prevent client URL handler addition in non-browser environments

- app/src/main/java/com/dlsc/jfxcentral2/app/pages/MobileRefreshPage.java
- app/src/main/java/module-info.java
- components/src/main/java/com/dlsc/jfxcentral2/components/CustomMarkdownView.java
- components/src/main/java/com/dlsc/jfxcentral2/components/PacksIconsView.java
- components/src/main/java/com/dlsc/jfxcentral2/utils/IkonliPackUtil.java
- components/src/main/java/module-info.java
- components/src/main/resources/com/dlsc/jfxcentral2/theme.css
- mobile/src/main/java/module-info.java
- pom.xml
- sampler/src/main/java/com/dlsc/jfxcentral2/demo/components/HelloSearchIkonGridView.java
This PR enhances the icon search functionality by allowing users to filter results by selected icon packs.
- All icon results from all packs were shown when searching by keyword (e.g. `arrow`)
- This led to overwhelming and often irrelevant matches, especially with common keywords
- A `SelectionBox` UI control is added to let users pick one or more icon packs (e.g., MaterialDesign, IcoMoon, FontAwesome)
- The search now returns icons only from the selected packs, making results more precise and manageable
- Improved usability of the icon explorer
- Better performance when dealing with large icon sets
- Easier to discover relevant icons in specific design systems
By default, all icon packs are selected, so the search still behaves as before — matching icons across all available packs
> Improve icon search by allowing filtering by selected icon packs
